.\" Manpage for math
.TH math 1 "5 October 2016" "1.0" "math manual"
.SH NAME
math \- command for mathematical calculation
.SH SYNOPSIS
math [--version | -v] [--help | -h]
.PP
math sum <args>
.PP
math factorial <arg>
.PP
math multiply <args> 
.PP
math divide <args> 
.SH DESCRIPTION
.BI math
is command line tool for mathematical calculation. It can be used for
   --> Addition
   --> Multiplication
   --> Factorial
   --> Division
.SH EXAMPLE
.PP
$ math sum 1 2 3 4 
.PP
$ math factorial 5
.PP
$ math multiply 2 3 4 
.PP
$ math divide 32.0 4 
.SH BUGS
https://github.com/rishikant42/math-fun
.SH AUTHOR
Rishi kant sharma
